Styling
Rishi-Mishra0704/bookstore-project pull request #5
Opened 2023-04-14 10:19 UTC by Rishi-Mishra0704

- Add styles to the navbar
- Add styles to book section
- Add styles to the form 
- Add a randomizer to change the category
- Add a randomizer to change the percentage
- Add a randomizer to change the chapter number

2023-04-14 11:16 UTC, PinkMoon25 requested changes
Hi @Rishi-Mishra0704 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/zyjCXPXNo39i0CB467/giphy.gif"/>

## Highlights
Linter checks :heavy_check_mark: 
gitflow :heavy_check_mark: 
functionality :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- [ ] Please fix this heading in the Readme so that it mentions the correct project name :point_down: 
![image](https://user-images.githubusercontent.com/97521557/232029493-365b53d3-97fe-4c83-8019-80abc6c8a21b.png)

- [ ] please fix the description here in the readme :point_down: 
![image](https://user-images.githubusercontent.com/97521557/232029599-dde2a98e-9e3d-47d6-b67d-6a5f82114943.png) 

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-14 11:16 UTC, PinkMoon25 commented on src/components/css/Book.module.css
- [ ] Good job styling the application, however as mentioned in the requirements **'Your final design should match Zeplin's design (this includes all elements + the same styling)'** l have some suggestions to make it match the original design please see :point_down: 
![image](https://user-images.githubusercontent.com/97521557/232028192-da296a27-6bf1-440c-a8a0-d73eb65c03ac.png)

Tip: you can use [the project created by one of Microverse students - Usman Suleiman Babakolo](https://pedantic-beaver-cb923b.netlify.app/#/). to get the right styling requirements just by inspecting it in the browser.

1. please fix the background color so we see each book card as in the original design
2. The book title seems to be different fro the original design, please fix the font-weight for it
3. Make sure the Add book form matches the original design, including the Input fields and the neccesarry margin and padding(missing space)

Please see the original design :point_down: 
![image](https://user-images.githubusercontent.com/97521557/232028932-616b9375-aa90-4e37-9074-2caeb5251506.png)

2023-04-14 12:37 UTC, Rishi-Mishra0704 commented on src/components/css/Book.module.css
@PinkMoon25 I understood the rest of changes but me the input field is looking fine , can you please specify the issue properly?

2023-04-14 13:52 UTC, PinkMoon25 commented on src/components/css/Book.module.css
hi @Rishi-Mishra0704 , sure the issue is the width please see :point_down: 
![image](https://user-images.githubusercontent.com/97521557/232062135-ac3c1409-b8d9-4c8f-89d6-94abf422a8b8.png)

2023-04-14 14:19 UTC, Rishi-Mishra0704 commented on src/components/css/Book.module.css
Thank you so much for clarifying

2023-04-14 16:15 UTC, NahnahAJ requested changes
## Project Status: CHANGES REQUIRED :recycle: 
Hi @Rishi-Mishra0704 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which haven't been addressed yet.
<img src="https://media1.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

 ## Highlights
- No linter errors :heavy_check_mark: 
- Good use of GitFlow :heavy_check_mark: 
- Professional README :heavy_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @NahnahAJ in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-14 16:15 UTC, NahnahAJ commented on src/components/css/Book.module.css
> +}
- [ ] Great job so far @Rishi-Mishra0704 I see you tried to implement the previous reviewer's suggestion but some of them weren't done properly and in the process, some elements lost their original styles but no need to worry I have made sure to point out each of them in the screenshot below :+1: 
- Your Design
![image](https://user-images.githubusercontent.com/102699958/232098771-09a2fbe7-cc11-4c3f-9c02-f711e2ac1b3b.png)

- The Original Design
![image](https://user-images.githubusercontent.com/102699958/232098984-f8610b61-5b6f-4d3f-a685-aa1deb91093b.png)

2023-04-15 09:26 UTC, sumairq approved these changes
### Hi @Rishi-Mishra0704 , 

<img src="https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Git flow
✔️Descriptive PR
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-15 10:00 UTC, merged